# Generated by Django 2.1.7 on 2019-02-26 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OB_no', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('ID_no', models.IntegerField()),
                ('contacts', models.IntegerField()),
                ('area_of_stay', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('date_and_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('nature_of_crime', models.CharField(max_length=50)),
                ('description_of_crime', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=50)),
                ('investigating_officer', models.CharField(max_length=50)),
                ('section_of_CPC_offence', models.CharField(max_length=100)),
            ],
        ),
    ]
