# Generated by Django 2.1.7 on 2019-03-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('ID_no', models.IntegerField()),
                ('nationality', models.CharField(max_length=50)),
                ('offences', models.CharField(max_length=250)),
            ],
        ),
    ]
