# Generated by Django 2.1.7 on 2019-03-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcapp', '0002_criminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=100)),
                ('pc_no', models.IntegerField()),
            ],
        ),
    ]
