# Generated by Django 2.1.7 on 2019-03-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcapp', '0003_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pcapp.Record'),
        ),
    ]
