# Generated by Django 2.1.7 on 2019-03-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcapp', '0004_criminal_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_of_crime', models.CharField(max_length=50)),
                ('description_of_crime', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=50)),
                ('investigating_officer', models.CharField(max_length=50)),
                ('section_of_CPC_offence', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='criminal',
            name='record',
        ),
        migrations.RemoveField(
            model_name='record',
            name='description_of_crime',
        ),
        migrations.RemoveField(
            model_name='record',
            name='investigating_officer',
        ),
        migrations.RemoveField(
            model_name='record',
            name='nature_of_crime',
        ),
        migrations.RemoveField(
            model_name='record',
            name='section_of_CPC_offence',
        ),
        migrations.RemoveField(
            model_name='record',
            name='status',
        ),
        migrations.AddField(
            model_name='crime',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pcapp.Record'),
        ),
        migrations.AddField(
            model_name='criminal',
            name='crime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pcapp.Crime'),
        ),
    ]
