# Generated by Django 2.1.7 on 2019-04-18 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcapp', '0005_auto_20190319_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pcapp.Record'),
        ),
    ]
